sqlite:
  :adapter: sqlite
  :dbfile: ':memory:'
sqlite3:
  :adapter: sqlite3
  :dbfile: ':memory:'
test:
  :adapter: sqlite3
  :dbfile: ':memory:'
postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: most_popular_test
  :min_messages: ERROR
mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password:
  :database: most_popular_test